name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger action on pull request to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # The AWS region you're using

      # Create the ECR repository if it does not exist
      - name: Create ECR Repository (if not exists)
        run: |
          aws ecr describe-repositories --repository-name react-app || \
          aws ecr create-repository --repository-name react-app

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        run: |
          echo "Logging in to ECR..."
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 322736530834.dkr.ecr.eu-north-1.amazonaws.com
      # Build the Docker image
      - name: Build Docker image
        run: docker build -t 322736530834.dkr.ecr.ap-southeast-2.amazonaws.com/react-app:latest .

      # Push Docker image to AWS ECR
      - name: Push Docker image to AWS ECR
        run: |
          docker push 322736530834.dkr.ecr.ap-southeast-2.amazonaws.com/react-app:latest
