name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger action on pull request to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # The AWS region you're using

      # Debugging step to check if credentials are passed correctly
      - name: Debug AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_REGION: ap-southeast-2"

      # Log in to AWS ECR
      - name: Log in to Amazon ECR
        run: |
          echo "Logging in to ECR..."
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 024848442252.dkr.ecr.ap-southeast-2.amazonaws.com

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t 024848442252.dkr.ecr.ap-southeast-2.amazonaws.com/my-ecr-repository:latest .

      # Push the Docker image to AWS ECR
      - name: Push Docker image to AWS ECR
        run: |
          docker push 024848442252.dkr.ecr.ap-southeast-2.amazonaws.com/my-ecr-repository:latest
